# Generated by Django 3.2.11 on 2022-04-14 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=1000, verbose_name='Содержание')),
                ('dataCreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('dateEdit', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('activity', models.BooleanField(default=False, verbose_name='Флаг активности')),
                ('tag', models.CharField(blank=True, default='Новость', max_length=50, verbose_name='Тэг')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя')),
                ('text', models.TextField(max_length=400, verbose_name='Текст комментария')),
                ('id_news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='app_news.news', verbose_name='Комментарий')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_comment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
