# Generated by Django 3.2.11 on 2022-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='moderate',
            field=models.CharField(choices=[('R', 'Запрос на публикацию отправлен'), ('V', 'Опубликована'), ('N', 'Отклонено')], default='R', max_length=2),
        ),
    ]
