# Generated by Django 3.2.15 on 2022-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_shopping',
            name='status',
            field=models.CharField(choices=[('A', 'В корзине'), ('P', 'Оплачено'), ('C', 'Отмена')], default='A', max_length=1, verbose_name='Buy status'),
        ),
    ]
