# Generated by Django 3.2.15 on 2022-08-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_history_shopping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balanceShopping',
            field=models.FloatField(blank=True, default=0, verbose_name='Balance shopping'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history_shopping',
            name='date_of_shopping',
            field=models.DateField(auto_now_add=True),
        ),
    ]
