# Generated by Django 4.0 on 2021-12-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_autor', models.CharField(db_index=True, max_length=150)),
                ('email_autor', models.CharField(max_length=150)),
                ('number_mobile_autor', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name_autor'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0, verbose_name='цена')),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to='advertisements_app.autor')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='advertisements_app.category')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['title'],
            },
        ),
    ]
