# Generated by Django 3.2.15 on 2022-08-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='Count rooms')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='Name house')),
                ('Address', models.CharField(blank=True, max_length=100, verbose_name='Address house')),
                ('Price', models.FloatField(blank=True, verbose_name='Price')),
                ('CountRooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_house.countrooms', verbose_name='Count rooms')),
            ],
        ),
        migrations.CreateModel(
            name='TypeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='Type house')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='Name news')),
                ('House', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_house.house', verbose_name='House')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='TypeHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_house.typehouse', verbose_name='Type house'),
        ),
    ]
