# Generated by Django 3.2.15 on 2022-08-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_house', '0002_auto_20220820_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descriprion',
            new_name='description',
        ),
    ]
