# Generated by Django 4.0 on 2021-12-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_adverеtisementtype_alter_advertisement_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdverеtisementType',
            new_name='AdvertisementStatus',
        ),
        migrations.RenameModel(
            old_name='AdverеtisementStatus',
            new_name='AdvertisementType',
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advert',
        ),
    ]
