# Generated by Django 4.0 on 2021-12-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_rename_adverеtisementtype_advertisementstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adStatus', to='advertisements.advertisementstatus'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adType', to='advertisements.advertisementtype'),
        ),
    ]
