# Generated by Django 4.0 on 2021-12-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_alter_advertisement_status_alter_advertisement_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementStatus',
            new_name='AdveretisementStatus',
        ),
        migrations.RenameModel(
            old_name='AdvertisementType',
            new_name='AdveretisementType',
        ),
    ]
