# Generated by Django 4.0 on 2021-12-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_rename_advertisementstatus_adveretisementstatus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdveretisementStatus',
            new_name='AdvertisementStatus',
        ),
        migrations.RenameModel(
            old_name='AdveretisementType',
            new_name='AdvertisementType',
        ),
    ]
