# Generated by Django 4.0 on 2021-12-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
