# Generated by Django 3.2.11 on 2022-05-25 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name shop')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, verbose_name='balance')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date_of_birth')),
                ('telephone_number', models.CharField(blank=True, max_length=12, verbose_name='telephone_number')),
                ('about_myself', models.CharField(blank=True, max_length=300, verbose_name='about_myself')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name product')),
                ('price', models.FloatField(blank=True, verbose_name='price')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='category')),
                ('shop', models.ManyToManyField(to='app_store.Shop')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='History_shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_shopping', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, verbose_name='count')),
                ('total', models.FloatField(blank=True, verbose_name='total')),
                ('product', models.ManyToManyField(to='app_store.Product')),
                ('shop', models.ManyToManyField(to='app_store.Shop')),
            ],
            options={
                'verbose_name': 'history shopping',
                'verbose_name_plural': 'history shopping',
            },
        ),
        migrations.CreateModel(
            name='Action_and_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name action')),
                ('type', models.CharField(choices=[('А', 'Акция'), ('П', 'Предложение')], default='А', max_length=1)),
                ('text_action', models.CharField(blank=True, max_length=200, verbose_name='text')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'action and offer',
                'verbose_name_plural': 'actions and offers',
            },
        ),
    ]
