# Generated by Django 3.2.11 on 2022-05-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_alter_history_shopping_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_shopping',
            name='product',
        ),
        migrations.AddField(
            model_name='history_shopping',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.product', verbose_name='product'),
        ),
        migrations.RemoveField(
            model_name='history_shopping',
            name='shop',
        ),
        migrations.AddField(
            model_name='history_shopping',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.shop', verbose_name='shop'),
        ),
    ]
